[package]
name = "macro_definitions"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
proc-macro = true

[dependencies]
syn = "2.0.65"
proc-macro2 = "1.0.81"
darling = "0.20.9"
